- name: install postgresql
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- name: create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: >
    name=sonar
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'

- name: create db user
  sudo: yes
  sudo_user: postgres
  postgresql_user: >
    name=sonar
    password=sonar
    db=sonar
    role_attr_flags=CREATEDB,NOSUPERUSER
    priv=ALL

- name: add pg_hba.conf
  sudo: yes
  template: >
    src=pg_hba.conf.j2
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    force=yes
  notify:
    - restart postgresql

