- name: add jenkins apt-key
  sudo: yes
  apt_key: >
    url='https://jenkins-ci.org/debian/jenkins-ci.org.key' 
    state=present

- name: add jenkins apt repository
  sudo: yes
  apt_repository: >
    repo='deb http://pkg.jenkins-ci.org/debian binary/' 
    state=present

- name: install jenkins
  sudo: yes
  apt: >
    pkg=jenkins
    state=latest

- name: ensure service is running
  service: >
    name=jenkins
    state=started

- name: allow connection to jenkins server
  sudo: yes
  ufw: >
    proto=tcp 
    port={{ jenkins_web_port }} 
    rule=allow
